### ISSUE TITLE
only the first image will load after it will struck 

### ISSUE THREAD

**Issue by brnandhu001** [mohitk05/react-insta-stories#229] opened 2022-08-02 03:58 UTC

**Comment by chaitan94** [comment] 2022-09-27 08:47
This is a duplicate of #214. As mentioned in [a comment](https://github.com/mohitk05/react-insta-stories/issues/214#issuecomment-1159517781) in the other issue, turning off react strict mode is a workaround for this issue as of now.

**Comment by exotexot** [comment] 2022-12-06 16:57
Removing Strict Mode didn't solve the issue for me...

**Comment by mohitk05** [comment] 2023-03-17 19:54
Hello, please update to v2.5.0 which includes a fix for this issue.

**Closed by mohitk05** 2023-03-17 19:54 UTC
